language: java
jdk:
- oraclejdk8
before_script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=indrabasak-github
  -Dsonar.login=$SONAR_TOKEN
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
env:
  global:
    secure: HXfawP1gKNmVYH2XDxFKScK4U3dSc3ryCoUpPIGojTTsqpitalq50maUfQAGDoxZVLTxxupecomaqGVOnpqgYJvHPsUjJntGw1npge66sZVJ/g2e2ITKYXkg6ArZukIbzsrAP/uLCB2ajpmztNeoypy01d/i6DbuMIM66gGoOKsiWQ4ytZx4Uq19idzj37BPfzJuznreKzEvE+xnOOmBvmnEMUABQgO39GL+O4GDtHNCJT3ygAUR/zgrzwLWxYAO4D7dDQS0xLnOZWnpoe2InKHkyLuL3bYAQznpN1V7PO7dMfPxvsyJuBor4SPrD7hXOTcrhufXj1RA3Ilbf6sgaJihbAc57QP2z5NJHBVapv4RNQyKBbIkC3gjyvFZMpJjk28BvnITAUQgQmCMHv5FPL64MbR8MX2emf/YUK81sZDWjoEKgUXBne4UsMsaIlESKjM80RUwMZNExu4E7+zTBc/cW04vs6u+ope1kuyBTRjBVlkuwtjS7h7qCpkXF+dur6cuvI7eBmlLH+0PQlDb8bRlzGdGiGs2X2t2E9hsaJsGgibrixpnNohdQSIHKFcePNrnpO/KeZ4TAW/t4lQ+uXX0DciCJyMpbG+02+a4bNpsM4GRhsCwnU895NE1weC9qO6w5wFTkXhhlJE2vL783QuDlBJFOtDtWdH/OtMFyjE=
